# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxQpN-IcCCTAHDWcwL8qDhanybPJ2bdT
"""

# app.py
import json
from typing import List, Dict, Any, Tuple
import operator
import streamlit as st

# -------------------------------------------------
# 1) Minimal Rule Engine (Scholarship Version)
# -------------------------------------------------

OPS = {
    "==": operator.eq,
    "!=": operator.ne,
    ">": operator.gt,
    ">=": operator.ge,
    "<": operator.lt,
    "<=": operator.le,
    "in": lambda a, b: a in b,
    "not_in": lambda a, b: a not in b,
}

# ----------------------------
# Scholarship Rules (Given in Assignment)
# ----------------------------

DEFAULT_RULES: List[Dict[str, Any]] = [
    {
        "name": "Top merit candidate",
        "priority": 100,
        "conditions": [
            ["cgpa", ">=", 3.7],
            ["co_curricular_score", ">=", 80],
            ["family_income", "<=", 8000],
            ["disciplinary_actions", "==", 0]
        ],
        "action": {
            "decision": "AWARD_FULL",
            "reason": "Excellent academic & co-curricular performance, with acceptable need"
        }
    },
    {
        "name": "Good candidate - partial scholarship",
        "priority": 80,
        "conditions": [
            ["cgpa", ">=", 3.3],
            ["co_curricular_score", ">=", 60],
            ["family_income", "<=", 12000],
            ["disciplinary_actions", "<=", 1]
        ],
        "action": {
            "decision": "AWARD_PARTIAL",
            "reason": "Good academic & involvement record with moderate need"
        }
    },
    {
        "name": "Need-based review",
        "priority": 70,
        "conditions": [
            ["cgpa", ">=", 2.5],
            ["family_income", "<=", 4000]
        ],
        "action": {
            "decision": "REVIEW",
            "reason": "High need but borderline academic score"
        }
    },
    {
        "name": "Low CGPA – not eligible",
        "priority": 95,
        "conditions": [
            ["cgpa", "<", 2.5]
        ],
        "action": {
            "decision": "REJECT",
            "reason": "CGPA below minimum scholarship requirement"
        }
    },
    {
        "name": "Serious disciplinary record",
        "priority": 90,
        "conditions": [
            ["disciplinary_actions", ">=", 2]
        ],
        "action": {
            "decision": "REJECT",
            "reason": "Too many disciplinary records"
        }
    }
]


# ----------------------------
# Rule Engine Functions
# ----------------------------

def evaluate_condition(facts: Dict[str, Any], cond: List[Any]) -> bool:
    """Evaluate a single condition: [field, op, value]."""
    if len(cond) != 3:
        return False
    field, op, value = cond
    if field not in facts or op not in OPS:
        return False
    try:
        return OPS[op](facts[field], value)
    except Exception:
        return False


def rule_matches(facts: Dict[str, Any], rule: Dict[str, Any]) -> bool:
    """Check if all conditions in a rule are satisfied (AND logic)."""
    return all(evaluate_condition(facts, c) for c in rule.get("conditions", []))


def run_rules(facts: Dict[str, Any], rules: List[Dict[str, Any]]) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
    """
    Returns:
    - best_action (highest priority matched)
    - fired_rules (all matched)
    """
    fired = [r for r in rules if rule_matches(facts, r)]

    if not fired:
        return {"decision": "NO_DECISION", "reason": "No rules matched"}, []

    fired_sorted = sorted(fired, key=lambda r: r.get("priority", 0), reverse=True)
    best = fired_sorted[0]["action"]
    return best, fired_sorted


# -------------------------------------------------
# 2) Streamlit UI (Scholarship Eligibility App)
# -------------------------------------------------

st.set_page_config(page_title="Scholarship Rule-Based System", layout="wide")
st.title("🎓 Scholarship Eligibility Rule-Based System")
st.caption("Enter student details, edit rules (optional), and evaluate scholarship eligibility.")

# ----------------------------
# Sidebar Input Fields
# ----------------------------

with st.sidebar:
    st.header("Applicant Information")

    cgpa = st.number_input("CGPA", min_value=0.0, max_value=4.0, step=0.01, value=3.0)
    family_income = st.number_input("Family Income (RM)", min_value=0, max_value=50000, step=100, value=8000)
    co_score = st.number_input("Co-Curricular Score (0–100)", min_value=0, max_value=100, step=1, value=70)
    service_hours = st.number_input("Community Service Hours", min_value=0, max_value=500, step=1, value=20)
    semester = st.number_input("Semester", min_value=1, max_value=12, step=1, value=4)
    disciplinary = st.number_input("Disciplinary Actions", min_value=0, max_value=10, step=1, value=0)

    st.divider()

    st.header("Rules (JSON Editable)")
    rules_text = st.text_area("Edit Rules Here", value=json.dumps(DEFAULT_RULES, indent=2), height=350)

    run = st.button("Evaluate", type="primary")


# ----------------------------
# Show Facts
# ----------------------------

facts = {
    "cgpa": float(cgpa),
    "family_income": int(family_income),
    "co_curricular_score": int(co_score),
    "community_service_hours": int(service_hours),
    "semester": int(semester),
    "disciplinary_actions": int(disciplinary)
}

st.subheader("Applicant Facts")
st.json(facts)

# ----------------------------
# Parse Rules
# ----------------------------

try:
    rules = json.loads(rules_text)
    assert isinstance(rules, list)
except Exception as e:
    st.error(f"Invalid JSON. Using default rules. Details: {e}")
    rules = DEFAULT_RULES

# ----------------------------
# Display Rules
# ----------------------------

st.subheader("Active Rules")
with st.expander("Show Rules"):
    st.code(json.dumps(rules, indent=2), language="json")

st.divider()

# ----------------------------
# Evaluation
# ----------------------------

if run:
    action, fired = run_rules(facts, rules)

    col1, col2 = st.columns([1, 1])
    with col1:
        st.subheader("Scholarship Decision")
        decision = action["decision"]
        reason = action["reason"]

        if decision == "AWARD_FULL":
            st.success(f"FULL SCHOLARSHIP — {reason}")
        elif decision == "AWARD_PARTIAL":
            st.info(f"PARTIAL SCHOLARSHIP — {reason}")
        elif decision == "REJECT":
            st.error(f"REJECTED — {reason}")
        else:
            st.warning(f"REVIEW REQUIRED — {reason}")

    with col2:
        st.subheader("Matched Rules (Highest Priority First)")
        if not fired:
            st.info("No rules matched.")
        else:
            for i, r in enumerate(fired, start=1):
                st.write(f"**{i}. {r['name']}** | Priority: {r['priority']}")
                st.caption(f"Action: {r['action']}")
                with st.expander("Conditions"):
                    for cond in r["conditions"]:
                        st.code(str(cond))

else:
    st.info("Adjust values and click **Evaluate**.")